kubectl apply -f kubernetes-manifests/pvc-redis-master.yaml 
kubectl apply -f kubernetes-manifests/redis-config.yaml
kubectl apply -f kubernetes-manifests/redis-master-deployment.yaml
kubectl apply -f kubernetes-manifests/redis-master-service.yaml
kubectl apply -f kubernetes-manifests/redis-master-network-policy.yaml
kubectl apply -f kubernetes-manifests/redis-statefulset.yaml 
kubectl apply -f kubernetes-manifests/redis-slave-network-policy.yaml 
kubectl apply -f kubernetes-manifests/guestbook-controller.json 
kubectl apply -f kubernetes-manifests/guestbook-service.json