kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi