apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: psp.privileged
spec:
  readOnlyRootFilesystem: false
  privileged: true
  allowPrivilegeEscalation: true
  hostNetwork: true
  hostIPC: true
  hostPID: true
  # required capabilities for TWISTLOCK defender daemonset
  allowedCapabilities:
  - NET_ADMIN 
  - SYS_ADMIN
  - SYS_PTRACE
  - AUDIT_CONTROL
  runAsUser:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  volumes:
  - '*'
---
apiVersion: v1
kind: Namespace
metadata:
  name: godmode
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:privileged
  namespace: godmode
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp.privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:privileged:binding
  namespace: godmode
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:privileged
subjects:
  - kind: Group
    name: system:serviceaccounts
    namespace: godmode
  
